import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const LanguageContext = createContext();

const translations = {
    en: {
        dashboard: "Dashboard",
        users: "Users",
        rooms: "Rooms",
        reservations: "Reservations",
        billing: "Billing",
        housekeeping: "Housekeeping",
        reports: "Reports",
        settings: "Settings",
        logout: "Logout",
        search: "Search room number...",
        all_types: "All Types",
        single: "Single",
        double: "Double",
        suite: "Suite",
        deluxe: "Deluxe",
        profile: "Profile",
        notifications: "Notifications",
        security: "Security",
        preferences: "Preferences",
        system_settings: "System Settings",
        save_changes: "Save Changes",
        language: "Language",
        theme: "Theme",
        currency: "Currency",
        luxury_stay: "LuxuryStay",
        change_password: "Change Password",
        current_password: "Current Password",
        new_password: "New Password",
        confirm_new_password: "Confirm New Password",
        update_password: "Update Password",
        password_strength_msg: "Update your password to keep your account secure. Use a strong password with at least 8 characters.",
        total_revenue: "Total Revenue",
        total_bookings: "Total Bookings",
        total_guests: "Total Guests",
        occupancy_rate: "Occupancy Rate",
        dashboard_overview: "Dashboard Overview",
        welcome_back_admin: "Welcome back, Administrator. Here's what's happening today.",
        export: "Export Report",
        quick_booking: "Quick Booking",
        recent_bookings: "Recent Bookings",
        view_all: "View all",
        booking_id: "Booking ID",
        guest: "Guest",
        room: "Room",
        check_in: "Check-in",
        status: "Status",
        amount: "Amount",
        room_status: "Room Status",
        available: "Available",
        dirty: "Dirty",
        maintenance: "Maintenance",
        growth_month: "Growth Month",
        view_analytics: "View analytics",
    },
    es: {
        dashboard: "Tablero",
        users: "Usuarios",
        rooms: "Habitaciones",
        reservations: "Reservas",
        billing: "Facturación",
        housekeeping: "Limpieza",
        reports: "Informes",
        settings: "Ajustes",
        logout: "Cerrar sesión",
        search: "Buscar número de habitación...",
        all_types: "Todos los tipos",
        single: "Sencilla",
        double: "Doble",
        suite: "Suite",
        deluxe: "Lujo",
        profile: "Perfil",
        notifications: "Notificaciones",
        security: "Seguridad",
        preferences: "Preferencias",
        system_settings: "Ajustes del sistema",
        save_changes: "Guardar cambios",
        language: "Idioma",
        theme: "Tema",
        currency: "Moneda",
        luxury_stay: "EstanciaDeLujo",
        change_password: "Cambiar contraseña",
        current_password: "Contraseña actual",
        new_password: "Nueva contraseña",
        confirm_new_password: "Confirmar nueva contraseña",
        update_password: "Actualizar contraseña",
        password_strength_msg: "Actualice su contraseña para mantener su cuenta segura. Use una contraseña sólida de al menos 8 caracteres.",
    },
    fr: {
        dashboard: "Tableau de bord",
        users: "Utilisateurs",
        rooms: "Chambres",
        reservations: "Réservations",
        billing: "Facturation",
        housekeeping: "Ménage",
        reports: "Rapports",
        settings: "Paramètres",
        logout: "Déconnexion",
        search: "Rechercher un numéro...",
        all_types: "Tous les types",
        single: "Simple",
        double: "Double",
        suite: "Suite",
        deluxe: "Luxe",
        profile: "Profil",
        notifications: "Notifications",
        security: "Sécurité",
        preferences: "Préférences",
        system_settings: "Paramètres du système",
        save_changes: "Enregistrer",
        language: "Langue",
        theme: "Thème",
        currency: "Devise",
        luxury_stay: "SéjourDeLuxe",
        change_password: "Modifier le mot de passe",
        current_password: "Mot de passe actuel",
        new_password: "Nouveau mot de passe",
        confirm_new_password: "Confirmer le mot de passe",
        update_password: "Mettre à jour le mot de passe",
        password_strength_msg: "Mettez à jour votre mot de passe pour sécuriser votre compte. Utilisez un mot de passe fort d'au moins 8 caractères.",
    },
    ur: {
        dashboard: "ڈیش بورڈ",
        users: "صارفین",
        rooms: "کمرے",
        reservations: "ریزرویشن",
        billing: "بلنگ",
        housekeeping: "ہاؤس کیپنگ",
        reports: "رپورٹس",
        settings: "سیٹنگز",
        logout: "لاگ آؤٹ",
        search: "کمرہ نمبر تلاش کریں...",
        all_types: "تمام اقسام",
        single: "سنگل",
        double: "ڈبل",
        suite: "سویٹ",
        deluxe: "ڈی لکس",
        profile: "پروفائل",
        notifications: "نوٹیفکیشن",
        security: "سیکیورٹی",
        preferences: "ترجیحات",
        system_settings: "سسٹم سیٹنگز",
        save_changes: "تبدیلیاں محفوظ کریں",
        language: "زبان",
        theme: "تھیم",
        currency: "کرنسی",
        luxury_stay: "لگژری اسٹے",
        change_password: "پاس ورڈ تبدیل کریں",
        current_password: "موجودہ پاس ورڈ",
        new_password: "نیا پاس ورڈ",
        confirm_new_password: "نیا پاس ورڈ تصدیق کریں",
        update_password: "پاس ورڈ اپ ڈیٹ کریں",
        password_strength_msg: "اپنے اکاؤنٹ کو محفوظ رکھنے کے لیے اپنا پاس ورڈ اپ ڈیٹ کریں۔ کم از کم 8 حروف والا مضبوط پاس ورڈ استعمال کریں۔",
        total_revenue: "کل آمدنی",
        total_bookings: "کل بکنگ",
        total_guests: "کل مہمان",
        occupancy_rate: "کمروں کی شرح",
        dashboard_overview: "ڈیش بورڈ کا جائزہ",
        welcome_back_admin: "خوش آمدید، ایڈمنسٹریٹر۔ آج کی صورتحال یہ ہے۔",
        export: "رپورٹ ایکسپورٹ کریں",
        quick_booking: "فوری بکنگ",
        recent_bookings: "حالیہ بکنگ",
        view_all: "سب دیکھیں",
        booking_id: "بکنگ ID",
        guest: "مہمان",
        room: "کمرہ",
        check_in: "آمد",
        status: "صورتحال",
        amount: "رقم",
        room_status: "کمرے کی صورتحال",
        available: "دستیاب",
        dirty: "گندہ",
        maintenance: "مرمت",
        growth_month: "ماہانہ اضافہ",
        view_analytics: "تجزیہ دیکھیں",
    },
};

export const LanguageProvider = ({ children }) => {
    const { user } = useAuth();
    const [lang, setLang] = useState('en');

    useEffect(() => {
        if (user?.preferences?.language) {
            setLang(user.preferences.language);
        }
    }, [user]);

    const t = (key) => {
        const set = translations[lang] || translations['en'];
        return set[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
